package: poliastro
platform: linux-64
engine:
  - python=3.5
  - python=3.6
before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels poliastro
  - conda install pytest
script:
  - conda install numpy numba>=0.23 astropy>=1.0 matplotlib scipy jplephem
  - pip install --no-deps .  # Test installation correctness
  - pytest -vv  # Test against installed code
