package: poliastro
script:
  - conda build buildscripts/condarecipe
build_targets:
  - conda
platform: 
  - linux-64
engine:
  - python=2.7 numpy=1.9
  - python=3.3 numpy=1.9
  - python=3.4 numpy=1.9
