package: poliastro
platform: linux-64
engine:
  - python=2.7
  - python=3.3
  - python=3.4
  - python=3.5
env:
  - NUMPY=1.9
  - NUMPY=1.10
before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels poliastro
  - conda install pytest
script:
  - conda install numpy=$NUMPY numba>=0.18 astropy>=1.0 matplotlib scipy jplephem
  - pip install -e .
  - py.test poliastro -vv
---
package: poliastro
platform: linux-64
engine: python=3.3
env: NUMPY=1.10
exclude: true
