# The only current way of using OS X virtual machines in Travis CI
# is setting up a generic environment
# This is not a problem because Python will be installed through conda

language: python

branches:
  only:
    - master
    - 0.3.x
    - 0.4.x
    - 0.5.x
    - 0.6.x

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6

addons:
  apt:
    packages:
      - pandoc

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install python3; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 -m venv venv; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then source venv/bin/activate; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install pandoc; fi

install:
  - pip install numpy  # Required
  - pip install pep8 mypy
  - pip install sphinx sphinx_rtd_theme nbsphinx ipython  # Install documentation dependencies
  - pip install .  # Test installation correctness

before_script:
  - pep8 setup.py src/  # Check PEP8 compliance
  - mypy --ignore-missing-imports --check-untyped-defs src/  # Check MyPy diagnostics

script:
  - python setup.py test -vv  # Test against installed code
  - sphinx-build -vW -b html docs/source _HTMLTest  # Test docs build

after_success:
  # Uninstall to test coverage against sources
  - pip uninstall poliastro -y
  - pip install -e .

  - NUMBA_DISABLE_JIT=1 python setup.py test -a "--cov"

  # Publish coverage
  - pip install codecov
  - codecov

sudo: false
