language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - pip install --upgrade pip setuptools
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors numpy astropy pytest
script:
  - python setup.py install
  - pytest -t tests
