# The only current way of using OS X virtual machines in Travis CI
# is setting up the environment for Objective-C
# This is not a problem because Python will be installed through conda

language: objective-c

env:
  matrix:
    - PYTHON=3.3 NUMPY=1.9
    - PYTHON=3.4 NUMPY=1.9
    - PYTHON=3.5 NUMPY=1.9
    - PYTHON=3.4 NUMPY=1.10
    - PYTHON=3.5 NUMPY=1.10

branches:
  only:
    - master
    - 0.3.x
    - 0.4.x

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels poliastro
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON
  - source activate test-environment
  - pip install coverage pytest pytest-cov codecov

install:
  - conda install numpy=$NUMPY numba>=0.18 astropy>=1.0 matplotlib scipy jplephem
  - python setup.py install  # Test setup.py correctness

script:
  - py.test -vv  # Test against installed code

after_success:
  - pip uninstall poliastro -y
  - python setup.py develop
  - NUMBA_DISABLE_JIT=1 py.test --cov
  - codecov

sudo: false
