# OS X trick inspired by
# https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791

language: python

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew tap derekkwok/python
        - brew uninstall python
        - brew install python35
        - virtualenv env -p python3.5
        - source env/bin/activate
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate

branches:
  only:
    - master
    - 0.3.x
    - 0.4.x
    - 0.5.x
    - 0.6.x

install:
  - pip install numpy  # Required
  - pip install .  # Test installation correctness
  - pip install sphinx sphinx_rtd_theme nbsphinx ipython  # Install documentation dependencies

script:
  - python setup.py test -vv  # Test against installed code
  - sphinx-build -vW -b html docs/source _HTMLTest #Test docs build

after_success:
  # Uninstall to test coverage against sources
  - pip uninstall poliastro -y
  - pip install -e .

  - NUMBA_DISABLE_JIT=1 python setup.py test --cov

  - codecov  # Publish coverage

sudo: false
