language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran
  - pip install --upgrade pip setuptools
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors numpy astropy pytest
script:
  - python setup.py install
  - cd poliastro/
  - py.test -rx tests/
