# The only current way of using OS X virtual machines in Travis CI
# is setting up the environment for Objective-C
# This is not a problem because Python will be installed through conda

language: objective-c

env:
  matrix:
    - PYTHON=2.7 NUMPY=1.9
    - PYTHON=3.3 NUMPY=1.9
    - PYTHON=3.4 NUMPY=1.9
    - PYTHON=2.7 NUMPY=1.10
    - PYTHON=3.4 NUMPY=1.10

branches:
  only:
    - master
    - 0.3.x

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON
  - source activate test-environment
  - conda install numpy=$NUMPY numba>=0.18 astropy>=1.0 matplotlib pytest pip coverage requests pyyaml scipy
  - conda install numpy=$NUMPY jplephem -c poliastro
  - pip install coveralls pytest-cov
  - pip install -e .    # Needed to use py.test properly

script:
  - py.test poliastro -vv
  - NUMBA_DISABLE_JIT=1 py.test --cov poliastro poliastro/tests poliastro/twobody/tests --cov-config .coveragerc

after_success:
  coveralls

sudo: false
