# The only current way of using OS X virtual machines in Travis CI
# is setting up the environment for Objective-C
# This is not a problem because Python will be installed through conda

language: objective-c

env:
  matrix:
    - PYTHON=2.7
    - PYTHON=3.3
    - PYTHON=3.4

branches:
  only:
    - master

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON
  - source activate test-environment
  - conda install numpy "numba>=0.18" "astropy>=1.0" matplotlib pytest pip coverage requests pyyaml scipy
  - conda install jplephem -c poliastro
  - pip install coveralls pytest-cov

script:
  - py.test -vv
  - NUMBA_DISABLE_JIT=1 py.test --cov poliastro

after_success:
  coveralls

sudo: false
