version: 2
jobs:
  quality:
    docker:
      - image: python:3.6

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: "check"

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m pip install tox

      - run:
          name: check quality
          command: |
            tox

  test_py36: &test-template  # See https://discuss.circleci.com/t/run-tests-on-multiple-versions-of-python/15462/2
    docker:
      - image: python:3.6

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: "py36,images"

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m pip install tox

      - run:
          name: run tests
          command: |
            FLIT_ROOT_INSTALL=1 MPLBACKEND=Agg tox  # Test against installed code

  test_py37:
    <<: *test-template
    docker:
      - image: python:3.7

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: "py37,images"

  coverage:
    docker:
      - image: python:3.6

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: "coverage"

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m pip install tox

      - run:
          name: run coverage
          command: |
            FLIT_ROOT_INSTALL=1 MPLBACKEND=Agg NUMBA_DISABLE_JIT=1 tox   # Test against sources

      - run:
          name: publish coverage
          command: |
            python3 -m pip install codecov
            codecov

  docs:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt update && sudo apt install --no-install-recommends pandoc texlive texlive-latex-extra texlive-fonts-recommended dvipng graphviz
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install .[dev,cesium]
            pip install https://github.com/Juanlu001/sphinx_rtd_theme/archive/avoid-require-redefinition.zip

      - run:
          name: build docs
          command: |
            . venv/bin/activate
            sphinx-build -vW -b html docs/source docs-html

      - store_artifacts:
          path: docs-html
          destination: docs-html

workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
      - test_py36:
          requires:
            - quality
      - test_py37:
          requires:
            - quality
      - coverage:
          requires:
            - quality
      - docs:
          requires:
            - test_py36
            - test_py37
