package:
  name: poliastro
  version: "0.5.0.dev0"

source:
  path: ../..
  #git_url: https://github.com/poliastro/poliastro
  #git_tag: master

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - numpy >=1.9
    - scipy
    - numba >=0.18
    - astropy >=1.0
    - jplephem
    - matplotlib
    - pytest

test:
  imports:
    - poliastro
    - poliastro.twobody

  requires:
    - pytest

about:
  home: https://poliastro.github.io/
  license: MIT License
  summary: "Python package for Orbital Mechanics"
