package:
  name: poliastro
  version: "0.3.0dev1"

source:
  path: ../..
  #git_url: https://github.com/Pybonacci/poliastro
  #git_tag: master

build:
  number: 1

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
    - numba
    - astropy
    - matplotlib

test:
  imports:
    - poliastro
    - poliastro.twobody

  requires:
    - pytest

about:
  home: https://pybonacci.github.io/poliastro
  license: Simplified BSD License
  summary: "Python package for Orbital Mechanics"
